[package]
name = "conservateur"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
poise = "0.5.5"
serde = "1.0.188"
serde_yaml = "0.9.25"
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
