services:
  app:
    image: none.local/conservateur:latest
    build:
      context: .
      dockerfile: Containerfile
    container_name: conservateur
    read_only: true
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
